---
- name: Playbook for tasks
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tasks:
    - name:  generate key 
      user:
        name: "{{item}}"
        generate_ssh_key: yes
      with_items:
        - ulan
        - miki
        - murat