---
- name: pulling keys from remote host to local
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: pulling keys
      fetch:  
        src: /home/{{item}}/.ssh/id_rsa.pub
        dest: /root/keyfiles/authorized_key.{{item}}.pub
        flat: true
      with_items:
        - ulan
        - miki
        - murat