---
- name: Playbook for tasks
  hosts: bastion
  become: yes
  become_method: sudo
  tasks: 
    - name: remove multiple users
      user: 
        name: "{{item}}"
        state: absent
        remove: yes 
      with_items:
        - ulan
        - miki
        - murat